/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiProjectsIdRouteImport } from './routes/api/projects/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsIdRoute = ApiProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/projects': typeof ApiProjectsRouteWithChildren
  '/api/projects/$id': typeof ApiProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/projects' | '/api/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/projects' | '/api/projects/$id'
  id: '__root__' | '/' | '/api/projects' | '/api/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiProjectsRoute: typeof ApiProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects/$id': {
      id: '/api/projects/$id'
      path: '/$id'
      fullPath: '/api/projects/$id'
      preLoaderRoute: typeof ApiProjectsIdRouteImport
      parentRoute: typeof ApiProjectsRoute
    }
  }
}

interface ApiProjectsRouteChildren {
  ApiProjectsIdRoute: typeof ApiProjectsIdRoute
}

const ApiProjectsRouteChildren: ApiProjectsRouteChildren = {
  ApiProjectsIdRoute: ApiProjectsIdRoute,
}

const ApiProjectsRouteWithChildren = ApiProjectsRoute._addFileChildren(
  ApiProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiProjectsRoute: ApiProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
